### PR TITLE
Update mail.css

### PR DESCRIPTION
**Pull request by jesseyuen**
Added 'display: block' on .container to aid responsive grid on resize.

### CODE REVIEW

**Comment by g13nn** [comment]
Hi jesseyuen,  

Thanks for the pull request, i have display:block; added to the mobile class.  I've just added it to the container class but i dont think it really needs it.  Have you found a use case where the display:block; is needed on the container class?

**Comment by jesseyuen** [comment]
Hi Glenn

I found that without display:block; on the container class, some of the
more complex grid layouts were breaking when resizing above/below the
breakpoint. I know resizing windows is something only developers do but
ensuring the grid layout on resize helped in testing!

Sorry for the delay in getting back to you.

**Comment by g13nn** [comment]
Hi jesseyuen,

Ok cool, come to think of it i've noticed this too.  Only sometimes does it not adapt correctly when resizing the window.  A quick refresh of the browser fixes this.  Might be worth adding this in.  I want to merge this pull request but "display" has been spelt incorrectly.  Are you able to correct?

**Comment by jesseyuen** [comment]
Hi Glenn

I closed this pull request and opened a new one. Cheers!

**Pull request closed without merging**
