### PR TITLE
Convert to unitless line-height

### PR DESCRIPTION
**Pull request by jameswilson**
Unitless line-heights will help with inheritance, specifically it helps to avoid cutting off text in sub-elements that have a larger default line height than that which was provided by pixels. Eg setting a 18px line height on a td with an h2 inside it will cut off the text. 

Additionally, on the spacer tds, using unitless line height gives the user/developer one less set of numbers to change, when they want to change the height of the spacer.

The formula I used to convert the line heights to unitless amounts was:

```
unitless line height = (line height in pixels) / (font size in pixels)
```

If the resulting ration created an irrational number, I rounded to the nearest decimal place.  For example:

```
20px / 14px =  1.4285714286  =>  1.4
```
### Test case

Add different level heading tags inside one of the Grid container tables, and use Litmus free to render in Outlook 2013 for example:
#### Input

Use the single-column grid, which defaults to font-size:12px line height: 18px

```
<!-- Start Container -->
<table width="600" cellpadding="0" cellspacing="0" border="0" class="container">
    <tr>
        <td width="600" class="mobile" style="font-family:arial; font-size:12px; line-height:18px;">
            <h1>Heading 1</h1>
            <h2>Heading 2</h2>
            <h3>Heading 3</h3>
            <h4>Heading 4</h4>
            <h5>Heading 5</h5>
            <h6>Heading 1</h6>
            <p>Paragraph text</p>
            <ul>
                <li>Unordered list item 1</li>
                <li>Unordered list item 2</li>
                <li>Unordered list item 3</li>
            </ul>
            <ol>
                <li>Ordered list item 1</li>
                <li>Ordered list item 2</li>
                <li>Ordered list item 3</li>
            </ol>
        </td>
    </tr>
</table>
<!-- End Container -->
```
#### Output

Both the `<h1>` and `<h2>` tags produce cutoff letters, because their default line-heights are greater than 18 pixels.

ol2013-vertical-allowed

### CODE REVIEW

**Comment by jameswilson** [comment]
In my test above if you change the line height on the `td` to unitless 1.5   (18/12 = 1.5) 

```
<td width="600" class="mobile" style="font-family:arial; font-size:12px; line-height:1.5;">
```

then Litmus produces the following:

ol2013-vertical-allowed-1

**Comment by g13nn** [comment]
Hi James Wilson,

Thank you for your research on this.  It's definitely a good approach if people wish to use h1 tags within a td  The email framework is setup so you don't need to use h1 tags for titles and instead inherit's it's styles from the surrounding td. 

If people like this approach and would like to see it added please have your say here!

**Comment by jameswilson** [comment]
To me, this seems like it would be a common approach, particularly for content coming from a CMS with a Rich Text editor.

**Comment by NivenRanchhod** [comment]
I personally think if you use anything other than straight body copy/wrap your text in p or span tags, which will all inherit the font styles from the wrapping tables and/or cells, you should be defining font-size and line-height again anyway.

I feel like h tags are pointless when we aren't hosting emails online for the specific purpose of web crawlers scanning our pages for SEO ranking.

That is just my personal view though. I build emails this way and haven't seen the need to test h tags on headings just to mimic web sites. But maybe I'm dropping the ball on accessibility with this thinking?

In saying all of that, a base 'percentage' attack on line heights makes sense, haha. 
Less onerous work for the end user to fiddle with this when they decide to change font sizes on everything, especially if not as html savvy as some of us and also don't test their emails like we do, religiously...

**Pull request closed without merging**
